server:
  port: 8887
  error:
    whitelabel:
      enabled: false
github:
  client:
    id: 2bcd63e763491ab33831
    secret: 5fe5be9b000bb422d77c9c769921ed3290778093
  redirect:
    uri: http://localhost:8887/callback
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community
    username: root
    password: rootroot
  #logging.level.root=DEBUG
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
mybatis:
  type-aliases-package: com.example.communication.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

ucloud:
  bucketName: communitybbs
  publicKey: TOKEN_4c2dea10-34c1-4a20-9ac9-4aeb6620ac40
  privateKey: a83b63b5-ad68-4af9-bd22-1930f56b6bd6
  region: cn-bj
  proxySuffix: ufileos.com
  expiresDuration: 2628000


