server:
  port: 8887
  error:
    whitelabel:
      enabled: false

github:
  client:
    id: 2bcd63e763491ab33831
    secret: 5fe5be9b000bb422d77c9c769921ed3290778093
  redirect:
    uri: http://117.50.177.50:8887/callback
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/community?socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC
    username: root
    password: rootroot
  #logging.level.root=DEBUG
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  profiles:
    active: dev #激活生产环境配置

mybatis:
  type-aliases-package: com.example.communication.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

ucloud:
  bucketName: communitybbs
  publicKey: TOKEN_4c2dea10-34c1-4a20-9ac9-4aeb6620ac40
  privateKey: a83b63b5-ad68-4af9-bd22-1930f56b6bd6
  region: cn-bj
  proxySuffix: ufileos.com
  expiresDuration: 2628000


logging:
  file:
    name: logs/my.log
    max-history: 10
    max-size: 100MB
  level:
    root: info
